# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

# Create an amazing Zsh config using antidote plugins.
source $HOME/dotfiles/antidote/antidote.zsh

# use short friendly names for antidoce downloads packages
zstyle ':antidote:bundle' use-friendly-names 'yes'

# conveniences for some older OMZ plugins, that export the old 
# directories to exist.
SHELL=zsh
ZSH=$(antidote home)
ZSH_CACHE_DIR="$ZSH/cache"
XDG_CACHE_HOME="$ZSH/cache"
[[ -d $ZSH_CACHE_DIR/completions ]] || mkdir -p $ZSH_CACHE_DIR/completions

antidote load

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# THIS SHOULD BE THE LAST THING IN THE FILE BECAUSE OF P10K'S FAST START
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

