is_macos() {
  [[ "$(uname)" == "Darwin" ]]
}

is_linux() {
  [[ "$(uname)" == "Linux" ]]
}


# Create zsh config using antidote plugins.
source $HOME/.config/dotfiles/antidote/antidote.zsh

# use short friendly names for antidote downloads packages
zstyle ':antidote:bundle' use-friendly-names 'yes'

# conveniences for some older OMZ plugins, that export the old 
# directories to exist.
SHELL=zsh
ZSH=$(antidote home)
ZSH_CACHE_DIR="$ZSH/cache"
XDG_CACHE_HOME=$ZSH_CACHE_DIR
[[ -d $ZSH_CACHE_DIR/completions ]] || mkdir -p $ZSH_CACHE_DIR/completions

antidote load

if [[ -r "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# THIS SHOULD BE THE LAST THING IN THE FILE BECAUSE OF P10K'S FAST START
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

