mode: terminal
shell: /bin/zsh
bootstrap_repo: https://github.com/jimweller/quiver-jim-bootstrap
dotfiles_repo: git@github.com:jimweller/dotfiles.git
resources:
  requests:
    cpu: "2"
    memory: 4Gi
    ephemeral_storage: 4Gi
  limits:
    cpu: "4"
    memory: 8Gi
    ephemeral_storage: 8Gi
storage:
  enabled: true
  size: 29Gi