#!/usr/bin/env bash

set -e

CONFIG="install.common.yaml"
CONFIG_MACOS="install.macos.yaml"
CONFIG_LINUX="install.linux.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! command -v python3 >/dev/null 2>&1; then
  echo "Python3 not found."

  echo -n "Detecting OS..."
  OS="$(uname -s)"
  echo " $OS"

  if [ "$OS" = "Linux" ]; then
    echo "Installing Python3 using apt-get..."
    sudo apt-get update && sudo apt-get install -y python3

  elif [ "$OS" = "Darwin" ]; then
    echo "Installing Python3 using Homebrew..."
    echo "    brew install python"

  else
    echo "Unknown OS: $OS. Cannot install Python automatically."
  fi
fi


cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"


# install the common configuration used by all OS
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"


# install OS specific configurations
# Detect OS and run the OS-specific profile
if [[ "$(uname)" == "Darwin" ]]; then
    echo "Running macOS-specific tasks..."
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_MACOS}"
elif [[ "$(uname)" == "Linux" ]]; then
    echo "Running Linux-specific tasks..."
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_LINUX}"
else
    echo "Unsupported OS: $(uname)"
fi