#ENC[AES256_GCM,data:55at8PisXhEBaOKrbAnuBEwjR2Zufo26eKZz8zCiWc4=,iv:5Vai0r/jdrJ2qb+8sM2P1uFNFipVu0XjdNS5ogM6llU=,tag:q8yptz3MBVGKCvd/G83eKg==,type:comment]
#
#ENC[AES256_GCM,data:5/0r5gqMrNyuvI8IhQyztS4Hh7Sc3Zo5ADhdY2Q8xy5kbVPHbnKxUw==,iv:waANcCJ+BIZbgidRZEx1RIK+fg5QiyyIS3yK2D/ZOQI=,tag:MDEG1RQsnRm9WKOK6+2QpQ==,type:comment]
#
#ENC[AES256_GCM,data:bLYG8mCkvEc=,iv:k/GTdZUzc7gr7SZjvjpoXakzA2aOqb3nq6rGDNNw4WA=,tag:U0HNshMpkjzGtsMxGOPkAA==,type:comment]
#ENC[AES256_GCM,data:4vzov1cFTQoq0w==,iv:N4eKNUclCCwWNe2qMsyvNNZZgzRi2403HiEKCDecggE=,tag:B6JphsEoIxavo3+bcZZlFQ==,type:comment]
#ENC[AES256_GCM,data:qh7uKn9mK0sZ7NpP8VjpBmUc+DTU6w9jmSEtadpOfD1qwDqm9G6yFt73S4bzGwFschc=,iv:nf23Fo3+BGPguni3gF6Ue648hgCm/S3MUwCdCjVo37U=,tag:5C/UIWsLkhFzfjNvIujZ8Q==,type:comment]
#ENC[AES256_GCM,data:r+xeC4t9cralpvJ57jcbzFhfR6QKvNKVh2Y0NH/YddRZgapW5uwD/UohmdSXyeOwOAeZvRNuiFwN30u3+gbMLpCyF+O18WDAcM5Y/+jD9YfFVYZxRD9DhjIX,iv:CbNCwt0PvHPqS7KBiJanJYW2pxnlv10g9wYY2zLbaN0=,tag:u4HtcZnBhbq3vJ+uHNTVBw==,type:comment]
#ENC[AES256_GCM,data:MWXoNXxxGomqNIoFZ9ySB935KAwlQLI=,iv:rANf2nWIGmIz38WKKScWexvli63s6JVob8TcerLS5ic=,tag:Xtsqn99FUyi8iDl29kVZ/w==,type:comment]
#ENC[AES256_GCM,data:NjJNntgKC/4+uFD7SqTZnuuJI+C6Jdg=,iv:2t6BKroob+z8/hP0v+GiO3uZYlMZTP//CX1SEjXVLEU=,tag:skOX8tLzxMBAG9wc4EaCbg==,type:comment]
spaces:
    - ENC[AES256_GCM,data:0sojdS5lJGqJdrM9iBvTrpu5qOzg7jzfc1E76QI=,iv:n/riHrXC9Uf42SKcCqpTb8uj9hbu5RDH2qo4dqowwo8=,tag:k3QyU5oeENY+mB9ZfvxPmQ==,type:comment]
    - ENC[AES256_GCM,data:jxkKf7W+Jg03ibXdDlNDKC2dJsTtO5MzZxIPsblXFLQ7BdCzIvdP,iv:m7xM/eItFsvxPRKaKLhNGbO04r+/sD/VIAUu3xVXHIM=,tag:77dOKugzv9NM5hPKR3mWZQ==,type:str]
    - ENC[AES256_GCM,data:ReRzAA==,iv:wklDwIoXVZ8AH3J7pWbmM0VLTN3vPKJ998absBezGlo=,tag:yZ/VuJHtpKAlP/pfU6uAJQ==,type:str]
    - ENC[AES256_GCM,data:w5o=,iv:y6qBlV4PX62jOMzcYXKawAP5ceQtUzMi+cqhvGV+TJE=,tag:Qu+d5yyTB+jpRKS9FWEL4g==,type:str]
    - ENC[AES256_GCM,data:TSAJ,iv:9AfhxU6H1htzJfOShZFsoi5ROF8vnpOEdepcRXN9Tfk=,tag:+0fkePpuQtPPObKk4awKiQ==,type:str]
    - ENC[AES256_GCM,data:phe/1w==,iv:sPWLSIA32kaNOr7GhZVI+7+AnboNHkzS0r4cWKYLW5s=,tag:0Cm1yjf+wZye0/Pz8JtTpQ==,type:str]
    - ENC[AES256_GCM,data:klm2,iv:uIZtmN/vGFIJcilc4vP4o1h8L1tdvCSOgG3UKcTXzDo=,tag:FDKXBu1MDTqht/URymlbVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa1BoeUgyTE9VUmQ1RHAw
            SVNOWW54YStkNlRWdC9TNjRQdW1RN0hIUzNBCko5SSt1UXl3bmJsSkRQdkZGMHln
            eVgvVytFRnFCZnFabjQvNE44K1F6c0UKLS0tIHFrVm9Jd1V1cTNaWkx0d3dvTlRa
            djcvZkRla0svYkhxTDVNMEozVEdoWUEKKfTj+NmNtFtfSuyGi5uYB5tUaXqe1tD2
            on1KV/UdBiAbKOxHg+kocC+Z6hLImHAwJG+PP/o3e89V/VFe9D461A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1acpjhysgq05ce884qyz5pju52qrth9nvr2ze2rqmreaggtjwzp7sq0jx3n
    lastmodified: "2026-10-09T05:05:49Z"
    mac: ENC[AES256_GCM,data:sN8KfFexvWGI6KnHorS6k64MwlOQowIDKjNad57J3SASiEfgK4+SWP9Y64tUcPrgOtm0sAnRYSJww55e2PzDZAUQYDGTecZJsfqcf3xfKek2+MzD/4qjR5G84wZ8xAAWKezVRvSBfziDWRF8pQvaAa2y4sqPMfI/Y1X2MqdMmEI=,iv:7d2eT3fw+liI4SxDi5viaWjTEitzeTcmb7Z/DxvTNrQ=,tag:PPY9B5ktvnmr5B4r2VTAkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
