#ENC[AES256_GCM,data:/Q9G/+Cq35c2qJ/LtAlT2LjTmmGlAvG+/PI0qx1+iCU=,iv:/bsoFCjtYz1nNXspfuH6PenKydouf4TCncnSU2Ex3ZI=,tag:q3OrdiOC10PQbxb0PMryLQ==,type:comment]
#
#ENC[AES256_GCM,data:WNIStbWwoyq0lenf59bCxTngd3e/pOls7sr3Dsx9BUnAj65jKqBKHg==,iv:4OmodiwJRHI1AtRkEWHafCyT5YB1dlfHdBUO3VLcL2Q=,tag:bl16v73ZYBwGkjVoBUAlRQ==,type:comment]
#
#ENC[AES256_GCM,data:wSQ1gNxvz9c=,iv:RbNGt3lfQ37g3rAndm+KZdFXaKgaWdrC+eRJYWPcKis=,tag:yYld1AOgy5pCMfx+jLd/wQ==,type:comment]
#ENC[AES256_GCM,data:suoXmEnsUqESTg==,iv:OmXAf71wGWMsR7k0kBReYOBxopPnSOXeojd/hUI+phw=,tag:YIVdkp9Spv2k39eA6dN31A==,type:comment]
#ENC[AES256_GCM,data:bjJTkmQcM3cFGdsNIW5Ol8FJlyTX8ntbfziuTtTP8JPNFbsRL0PWYO3WwyLmc2QSwDk=,iv:KICXTfs/ug7bX5wR4xYB3CcZMYmS2TEVawwFUzxWlHg=,tag:7sV9Ax0m2bL27nixOVnpcA==,type:comment]
#ENC[AES256_GCM,data:Jmx8NamVUo3sK90abWCrEmoYoEjvak/t6ROyvKIQ6slGIcZ+u17q/zMRmO4TCuGyu4ZGxap/zBwkp1QQKiUny+i2CUSQ/NfUCBorrXf4j7ti6mmEbQHjGzSt,iv:W2PW4b4XbAXHxV/d5+/QVqAld29JaeFvCd369fRp1x0=,tag:cQWyByqQNVMbDTRc59gknw==,type:comment]
#ENC[AES256_GCM,data:tyXhUbXg68JMl2XHgFejHWaakBpzz2I=,iv:6T9T1kfUAiZh2RYjJxTmhVcD7t8YvfGhtFqLLDAvMIg=,tag:StphOrnHtM6+5409HdXusg==,type:comment]
#ENC[AES256_GCM,data:jh9BcmTrZFCRbLarfnPySH5sJorTmHM=,iv:UJd1KpI+XzvwBDOhAg4uEvBN3lzVQ3mvonAMV7AxciE=,tag:01S2zGrHZd8R4bpEs9FlQw==,type:comment]
spaces:
    - ENC[AES256_GCM,data:x5+15MQ+nyM3+6+iOO9UbwkWJn1s5sV3JxJuV5w=,iv:dY1RZenEBy4qEFxikSeverMdDT75ETU3kMaMR+h2HRw=,tag:KiDxTdyLv/GzWJxTuUHpNQ==,type:comment]
    - ENC[AES256_GCM,data:DlUg1S7gKscDTa5uGNkCuoJ0E47+W8LewIexO0+OSBDU3Fk+Oo6K,iv:6ymVvH8D5eOQQscq2dZ5TxmKzfhaJN+WfaxRKuPq6ek=,tag:K0jgdE1nLcedoOwWnnDJYg==,type:str]
    - ENC[AES256_GCM,data:hBifMaygPouWSBhKbfVvxZreedFT/QINR8wy3B6hNPW04kWKKkWfT+mFm7xQpEZ8L/y/c0dDYLX5zAq+QdrFaw==,iv:FJocCtRf1SyoxojZzIIfK+MU1eF9L31C7/wf9vfmZ4g=,tag:ng1+H2u6J1mVj7Sg2OtW8w==,type:comment]
    - PENG:
        - ENC[AES256_GCM,data:iWnhc6xMhmUkJlbbaKYwJWV9EtAeJhixsrgw,iv:8QpgrinrCih1YXCiajGOCa+wCQQKgekEzFzRUdTBlr4=,tag:e45rBkUhY6Ly3jVZBSkv8Q==,type:str]
    - ENC[AES256_GCM,data:7lJvpcpzuTOKdEwGW/H4KYNFa9ygKH20zvqv4CHVBo7+HC+BE8tlIU6g0vAchulm/u9Q3gPMuhK7Wm2FloRYJ4I=,iv:pwffEE6FrSboZsKzEPjjJ1ySbnwcTk3+2Xs/AiiBPWQ=,tag:2YZZDlf8+eev981gs3dbHA==,type:comment]
    - DevX:
        - ENC[AES256_GCM,data:cfTvUoL+C0XshJVxR26bh7V9XtdeP4Km/xvZN4QU1Q==,iv:KIcrDCqTMPXhdgfWgb/YtBu6Y++oahS4xfoc5ZOwtqI=,tag:OY8f40RX2ag8YAr9FCxHqw==,type:str]
        - ENC[AES256_GCM,data:/lIFW7dJbty8xpgH+zXffTJr9lU=,iv:k9BVFTJ/hFA4Bv3DDX2Snb4kEkbZV5fo4HKid0DGWEM=,tag:ku8MZhZPEQOo26eFgHFjwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WWRGNlowam9JaVIxNWZo
            SmtFSXQyb0V3cjBaNDlRTmpZVnAwMW04K2tnCnlWa1J0R2dTeWw3d3phR3ZNZVJH
            U1NjNEE4OVQwKzRqc2FZcE05S09BM1UKLS0tIGlyZ1Y3OU54SHBCQzVvTStRSGFE
            Skp6ak4yR2YrM1lVeTA3OEJPQnRtdkkK4b+YEqhIMdqUWg8/iWxyuqySN9VuWjRg
            YsPmlChPy66h+BWHpeCL5gfG098F5PFMSbYdnOCctfKPOWlEbCE/PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1acpjhysgq05ce884qyz5pju52qrth9nvr2ze2rqmreaggtjwzp7sq0jx3n
    lastmodified: "2026-07-23T20:07:53Z"
    mac: ENC[AES256_GCM,data:VBWNFbOSgpv2tw8bT/s9Xt53NkUDJHTFXhffZ2OcM/ED4Lx/GxI9Y4oIi/BUFpAWySyFaRP3dzKJc/ggj2Eabq7AjlTccT5CXn4pTB/khGxOF525nwewiDQE8MskAS0ajrCCuNoh53jqPfC3ovHielqr7lPAV/wqXix55aCZWDE=,iv:m6jAE1eOrG5972l3S+wPyJV00PDdvs14LtvtDvhvvX0=,tag:3sLX5jplfW0WsaAJzWDssQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
